[package]
name = "renoir-mobile"
version = "0.1.0"
authors = ["Kyuno <kyuno@protonmail.com>", "aredden <alexander.h.redden@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.99"
libloading = "0.7.0"
json = "*"
regex = "1.0.0"
lazy_static = "1.4.0"
serde = "1.0.127"
serde_json = "1.0.66"