[package]
name = "cezanne-mobile-monitor"
version = "0.1.0"
authors = ["aredden <alexander.h.redden@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.99"
libloading = "0.7.0"
regex = "1.0.0"
lazy_static = "1.4.0"
serde = {version = "1.0.127", features = ["derive"]}
serde_json = "1.0.66"